### ISSUE TITLE
CPU spikes on eyowo.com

### ISSUE THREAD

**Issue by enolife** [eyowolabs/eyowo-js#9]
/*I didn't find a main repo for the website, so i had to open the issue here since it's the most updated*/

The website https://www.eyowo.com has a noticeable performance issue that consumes too much cpu especially on the first few minutes of loading the site.  You can confirm by checking your browser task manager.

This issue comes from using too many (15) infinite loops on animations in the style.css . https://www.eyowo.com/css/style.css .

I've been debugging for days until i traced it to this.

I hope you'll look into this . 
Thank You

**Browser Used: Chrome and Firefox on Windows 10**

**Comment by SeunAdelekan** [comment]
@enolife thanks for bringing this to our attention. The team will look into this and resolve accordingly. In the meantime, I'll be closing this issue as it does not relate directly to this library. Cheers.
